import sys
import spacy
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span
from spacy import displacy
import pdfplumber

with pdfplumber.open(sys.argv[1]) as pdf:
    pdf_full_text = ''
    for pdf_page in pdf.pages:
      single_page_text = pdf_page.extract_text()
      pdf_full_text = pdf_full_text + '\n' + single_page_text

red_flag_terms = ["exclusivity", "Exclusivity", "exclusively and in perpetuity", "Exclusively", "intellectual property rights", "Intellectual property rights", "right to sublicense", "material disclosure", "material connection"]
notice_terms = ["Attach", "attach", "Attached", "attached"]

nlp = spacy.load("en_core_web_sm")

# Only run nlp.make_doc to speed things up
#patterns = [nlp.make_doc(text) for text in terms]

red_flag_patterns = [nlp(term) for term in red_flag_terms] # process each term to create phrase pattern
#matcher.add("TerminologyList", patterns)
matcher = PhraseMatcher(nlp.vocab)
matcher.add('IMPORTANT', None, *red_flag_patterns) #add patterns to matcher

notice_patterns = [nlp(term) for term in notice_terms]
matcher.add('ATTACHMENT', None, *notice_patterns)


text = """
INFLUENCER AGREEMENT
This Agreement, executed on _________, 20__, is entered into by and between YOUR COMPANY, with an address of YOUR ADDRESS (hereinafter referred to as the “Company”) and __________________actor/model with an address of ________________________ (hereinafter, the “Influencer”). Company and Influencer may be referred to collectively as the “Parties.” For good and valuable consideration, receipt of which is hereby acknowledged, the Parties agree as follows:
1. ENGAGEMENT. Company hereby engages Influencer from the date of execution of this Agreement through and including the date(s) of performance (“the Term”) for the limited purpose of promoting certain brands and brand content, through Influencer’s social media outlets. The nature of the brand content to be promoted and the specific details and requirements of the promotion is outlined in the attached Schedule A. During the Term, Influencer agrees to be engaged for the purpose of promoting the brand content and to be bound by the guidelines as attached as Schedule B (“Guidelines”). Company hereby appoints Influencer as its representative on a non-exclusive, non-employee basis to endorse and promote its services to the target audience.
2. TERM. This Agreement shall have an initial term of one year and shall automatically renew for additional one-year terms thereafter unless either party provides thirty days prior written notice of its intention of nonrenewal.
OR
2. DATE OF PERFORMANCE. Parties agree that the Content will be disseminated on Influencer’s Outlets on __________________ (“Date(s) of Performance”). This dissemination on the specified date(s) will constitute the date(s) of performance and upon performance of the promotion of the Content and fulfillment of the terms, and upon payment of compensation by Company as outlined below, this Agreement shall terminate and Influencer’s rights to use the brand name
as described within this Agreement shall terminate as well.
3. DELIVERABLES. Influencer will deliver the agreed number of posts on the agreed platforms on behalf of Company as outlined in Schedule A. The Services shall conform to the specifications and instructions of Company as outlined in Schedule B, abide by the rules of the relevant social media platforms, and are subject to Company’s acceptance and approval. Company has a maximum of XX days to reject any deliverable in accordance with this Section and must notify Influencer within XX days of receipt of work that additional revisions and/or amendments will be requested.
4. OWNERSHIP. Influencer acknowledges and agrees that Company for the purpose of performing the Services under this Agreement shall own, exclusively and in perpetuity, all rights of whatever kind and character, throughout the universe and in any and all languages, in and to the videos, photographs, text and/or all works of similar nature produced, developed, or created by Influencer for this Agreement, and any and all intellectual property rights thereto, including trademarks, trade secrets, trade dress, design, mask work, copyrights, and patent rights (collectively, the “Content”), including the right to sublicense the Content to Company’s brand partners (the “Brand Affiliates”) . Notwithstanding the foregoing, Influencer may delete posts from his/her owned and/or controlled social media channels containing any Content after a period of thirty (90) days from post date.
5. USAGE. Company shall cause Influencer to grant to Company and to Brand Affiliates a limited, non-exclusive, royalty free, right and license to feature Content generated by Influencer as part of the Campaign (including influencer’s name and likeness) on Company’s and Brand Affiliates owned and controlled social media platforms and within third party digital and broadcast platforms and print platforms including but are not limited to: ad networks, email marketing, paid search listings, television, radio, newspapers, magazines and brochures, Facebook, Instagram, Twitter, Tumblr, YouTube, Pinterest, Vine, Google+ and website blogs during the term of this Agreement and for a period of twelve (12) months thereafter.
"""


doc = nlp(pdf_full_text)
matches = matcher(doc)
#import ipdb; ipdb.set_trace()
for match_id, start, end in matches:
    span = Span(doc, start, end, label=match_id)
    doc.ents = list(doc.ents) + [span] # add span to doc.ents
    #print(span.text)
print([(ent.text, ent.label_) for ent in doc.ents]) 

# Custom display - our custom defined keywords only
colors = {"IMPORTANT": "linear-gradient(90deg, #aa9cfc, #fc9ce7)", "ATTACHMENT": "linear-gradient(90deg, #B58ECC, #5DE6DE)"}
options = {"ents": ["IMPORTANT", "ATTACHMENT"], "colors": colors}
displacy.serve(doc, style="ent", options=options)

# Default display
#displacy.serve(doc, style="ent")